### PR TITLE
Update Jenkins to do daily/weekly builds

### PR DESCRIPTION
**Pull request by gmegh**

### CODE REVIEW

**Comment by teweitsai** [comment]
The Jenkins instance is unstable for the failure of `lsst_sphinx_bootstrap_theme`.
Let me know when you want to merge and I will do that for you as `admin`.
Thanks!

**Comment by suberlak** [comment]
Is this now following the recommended https://tssw-developer.lsst.io/development-guidelines/tools/jenkinsfile.html#jenkinsfile , or is  it only adding a daily/weekly builds ? Thanks for the update!

**Review by suberlak — APPROVED** [review]
Thanks for the update!

**Comment by gmegh** [comment]
I think it's only adding weekly/daily builds. @teweitsai if you could merge it that would be great!

**Pull request merged**
